server:
  port: ${PORT}
#  error:
#    whitelabel:
#      enabled: false
spring:
  jwt:
    secret: ${JWT_SECRET_KEY}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: ${DDL_TYPE}
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com  #SMTP sever host  : fix address
    port: 587 #SMTP server port : fix value
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true  # start TLS
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API}
#            redirect-uri: ${KAKAO_REDIRECT_URL}
            redirect-uri: ${OPERATION_KAKAO_REDIRECT_URL}
            authorization-grant-type: authorization_code
            client-authentication-method: none #client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  web:
    resources:
      add-mappings: false


aes:
  secret: ${AES_SECRET_KEY}
  algorithm: ${AES_ALGORITHM}

imp:
  api: ${IMP_API_KEY}
  secret : ${IMP_SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace  #show '?' in sql in console
